### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by mdczaplicki** [pietrodn/grpcio-mac-arm-build#3]
Any chances to get a wheel for python 3.7?

**Comment by pietrodn** [comment]
Hello! I [tried](https://github.com/pietrodn/grpcio-mac-arm-build/pull/4) to make a build for Python 3.7 as well, but cibuildwheel [fails](https://github.com/pietrodn/grpcio-mac-arm-build/actions/runs/3468516075/jobs/5794418678).

It appears that Apple Silicon support is available only for Python 3.8+.

> Only CPython 3.8 and newer support universal2 and arm64 wheels.
([source](https://cibuildwheel.readthedocs.io/en/stable/faq/#universal2))

> cibuildwheel supports cross-compiling universal2 and arm64 wheels on x86_64 runners. With the introduction of Apple Silicon, you now have several choices for wheels for Python 3.8+:
([source](https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon))

It might be possible to build a Python 3.7 wheel using other tools, but I don't have the time to investigate it at the moment. Any pull request will be welcome! 🙌🏼

**Comment by Kyle-sandeman-mrdfood** [comment]
Hi, I have been using python3.7 successfully for a while, which includes not needing the wheels from this repo (for that environment) since you'll be using the amd64 wheels which grpcio does ship.

See this StackOverflow answer for instructions to create a x64 environment with miniconda
https://stackoverflow.com/a/70219965/
If you don't use miniconda, I highly recommend it, but I am not familiar with how to do similar for pyenv or other python version management systems

**Comment by pietrodn** [comment]
Since Google is going to release official wheels also for Python 3.7 in the next release (see the [files of the yanked 1.52.0 release](https://pypi.org/project/grpcio/1.52.0/#files)), I don't think it's worth working on this. Closing :-)
